initial commit
FreeCourseJava/CurrencyExchangerJavaFirstProject pull request #1
Opened 2022-12-02 19:00 UTC by Aoascar

2022-12-05 17:14 UTC, neznaika38 commented on src/main/java/service/currencyList.java
> +public interface currencyList {
Правильно ли я понял, что я объявляю класс, имплементирую этот интерфейс? Тогда бы мне еще понять какие методы  будут.

2022-12-05 17:15 UTC, neznaika38 commented on src/main/java/entity/Currency.java
> +    private int currencyDenomination;
Его бы тоже в конструктор засунуть?

2022-12-05 17:25 UTC, Aoascar commented on src/main/java/entity/Currency.java
> +    private int currencyDenomination;
он уже в конструкторе

2022-12-05 17:25 UTC, Aoascar commented on src/main/java/service/currencyList.java
> +public interface currencyList {
методы же вроде Виктор прописывает? Или я?

2022-12-06 20:54 UTC, ivtcro commented on src/main/java/service/currencyList.java
> +public interface currencyList {
в этом интерфейсе есть один метод, но он ничего не возвращает - должег возвращать список валют

2022-12-06 21:02 UTC, ivtcro requested changes

2022-12-06 21:02 UTC, ivtcro commented on src/main/java/com/example/service/currencyList.java
> +    public void getCurrencyRates();
метод предлагаю по другому назвать - он же не только курсы возвращает

2022-12-06 21:17 UTC, tru10b commented on src/main/java/com/example/service/getCurrencies.java
> +}
я думаю, лучше вернуть String, в котором уже будет сидеть сжатый туда библиотекой gson весь набор курсов

2022-12-07 14:44 UTC, merged